# SITE CONFIG

# Basic meta
title: "Н0ВЫЙ КYРС"
description: "Общественное издание"
keywords: "новости, политика, общество, интервью, расследования, информация, события, факты, статья, экономика, заявление"
locale: "en_US"

# Paths
permalink: /:categories/:day-:month-:year-:title:output_ext
paginate_path: "/page/:num/"

# Items limits
paginate: 3
rssLimit: 20
